# These are supported funding model platforms

# github: [darkfriend]
custom: [
    'https://www.tinkoff.ru/cf/36wVfnMf7mo',
    'https://yoomoney.ru/to/410011413398643',
    'https://paypal.me/darkfriend'
]
